import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primaryBlack text-primaryWhite min-h-screen flex flex-col`}
      >
        {/* Header */}
        <header className="w-full bg-primaryGreen text-primaryWhite py-4 px-8 flex items-center justify-between shadow-md">
          <span className="text-2xl font-bold tracking-wide">Salone System</span>
          <nav className="space-x-6">
            <Link href="/" className="hover:underline">Dashboard</Link>
            <Link href="/customers" className="hover:underline">Customers</Link>
            <Link href="/employees" className="hover:underline">Employees</Link>
            <Link href="/bookings" className="hover:underline">Bookings</Link>
            <Link href="/products" className="hover:underline">Products</Link>
            <Link href="/sales" className="hover:underline">Sales</Link>
            <Link href="/payments" className="hover:underline">Payments</Link>
          </nav>
        </header>
        {/* Main Content */}
        <main className="flex-1 w-full max-w-7xl mx-auto px-4 py-8">
          {children}
        </main>
        {/* Footer */}
        <footer className="w-full bg-primaryGreen text-primaryWhite py-4 px-8 text-center text-sm">
          &copy; {new Date().getFullYear()} Salone System. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
